feat: new partners footer image
filesender/filesender pull request #1769
Opened 2024-01-08 16:44 UTC by WanderGomes

Adding new partners image

2024-01-16 13:29 UTC, WebSpider requested changes

2024-01-16 13:29 UTC, WebSpider commented on language/pt_BR/lang.php
> +$lang['an_initiative_by'] = 'Uma iniciativa por';
language translations are done in POEditor. Please update the string there, as any strings in the repo will get overwritten by POEditor exports, undoing these translations.

2024-01-23 18:39 UTC, WanderGomes commented on language/pt_BR/lang.php
> +$lang['an_initiative_by'] = 'Uma iniciativa por';
I checked on POEditor.com and I only have access to the FileSender 2.0 project, is that it?

I remember it was discussed in October about creating a new project for version 3.0. If this new project exists on POEditor, please invite me: wander.gomes@consultores.rnp.br

2024-01-23 18:53 UTC, WanderGomes commented on language/pt_BR/lang.php
> +$lang['an_initiative_by'] = 'Uma iniciativa por';
I checked on POEditor.com and I only have access to the FileSender 2.0 project, and I can't add new terms.
 
 I remember it was discussed in October about creating a new project for version 3.0. If this new project exists on POEditor, please invite me: wander.gomes@consultores.rnp.br

2024-01-25 09:07 UTC, WebSpider commented on language/pt_BR/lang.php
> +$lang['an_initiative_by'] = 'Uma iniciativa por';
Invitation was sent

2024-01-25 09:16 UTC, merged